export const serviceDefaults = [
  {
    name: "Custom Furniture",
    shortDescription: "High-quality custom furniture made from premium wood.",
    image: "/images/modern-wooden-kitchen-interior-steel-kitchen-faucet 2.png",
    category: "Furniture",
    price: "From 5,600 CZK",
    active: true,
    displayOrder: 1,
  },
  {
    name: "Wooden Staircases",
    shortDescription: "Elegant and durable staircases crafted to perfection.",
    image: "/images/video.png",
    category: "Construction",
    price: "Custom quote",
    active: true,
    displayOrder: 2,
  },
  {
    name: "Wooden Doors",
    shortDescription: "Custom wooden doors that combine beauty and security.",
    image: "/images/image (2).png",
    category: "Joinery",
    price: "From 8,000 CZK",
    active: true,
    displayOrder: 3,
  },
  {
    name: "Wood Flooring",
    shortDescription: "Premium wood flooring for a warm and natural look.",
    image: "/images/old-wood-grain-background 2.png",
    category: "Flooring",
    price: "From 1,700 CZK / m²",
    active: true,
    displayOrder: 4,
  },
  {
    name: "Outdoor Decking",
    shortDescription: "Weather-resistant wooden decking for outdoor spaces.",
    image: "/images/frames-for-your-heart-JDBVXignFdA-unsplash.jpg",
    category: "Outdoor",
    price: "Custom quote",
    active: false,
    displayOrder: 5,
  },
];
